---
- name: Deploy services using Satellite-managed repos
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: nginx
      when: ansible_distribution_major_version in ['8', '9']

    - role: chrony
      when: ansible_distribution_major_version == '8'

    - role: rsyslog
      when: ansible_distribution_major_version == '9'

